name = "two-sided-communication-with-coarrays"
version = "23.11.08"
license = "BSD"
author = ["Bradley Richardson"]
maintainer = "brad.richardson@lbl.gov"
copyright = "2023 Brad Richardson"

[dev-dependencies]
garden = { git = "https://gitlab.com/everythingfunctional/garden.git", tag = "v1.0.5" }
